### PR TITLE
Configure VPNKIT IP addresses automatically

### PR DESCRIPTION
**Pull request by Livius90**
WSL2 IP address is not fixed, it can be different after every WSL2 Linux starting. We can get the current VPNKIT IP addresses by "ip route show" and "grep" commands, always.

Further development should be in future that, we need to check VPNKIT_LOWEST_IP and VPNKIT_HIGHEST_IP because they are not allowed to be in conflict with others.

### CODE REVIEW

**Comment by sakai135** [comment]
The `VPNKIT_*_IP` values are for the network that VPNKit creates. They do not refer to the network that WSL 2 creates with Hyper-V.

What issues did you encounter with the default values? If the `192.168.65.0` subnet conflicts with your environment, you can provide different static values. 

I tried your changes, but they result in the following error and VPNKit was not able to establish a connection.

```
Error: Nexthop has invalid gateway.
```

**Comment by Livius90** [comment]
In every WSL2 Linux boot the Hyper-V ethernet got different IP address, 192.168.144.X or 172.168.X.X and so on. I could default check IPs again, but as i see, VPNKIT_*_IP must be defined according the IP address of the Hyper-V ethernet.

**Comment by sakai135** [comment]
The `VPNKIT_*_IP` values are only used within the network that VPNKit creates and is not visible outside of WSL 2. I don't think it should cause any issues with IP conflict with your LAN device. It is an arbitrary value that I just copied from Docker for Windows though, and if you find the need, you can edit your script to use different values.

**Comment by Livius90** [comment]
Do not need to merge it.

**Pull request closed without merging**
